# Generated by Django 4.2.3 on 2023-07-28 07:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('showroom', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Features',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horsepower', models.IntegerField(null=True)),
                ('topspeed', models.IntegerField(null=True)),
                ('abs', models.BooleanField(default=True)),
                ('transmission', models.CharField(choices=[('A', 'Automatic'), ('M', 'Manual')], max_length=1, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='brand',
            old_name='ShowRoom',
            new_name='showroom',
        ),
        migrations.RenameField(
            model_name='car',
            old_name='Model',
            new_name='model',
        ),
        migrations.RenameField(
            model_name='model',
            old_name='Brand',
            new_name='brand',
        ),
        migrations.RenameField(
            model_name='model',
            old_name='model',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='engine',
            name='Car',
        ),
        migrations.AddField(
            model_name='brand',
            name='contact',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='brand',
            name='estb',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='brand',
            name='owner',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='engine',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='showroom.engine'),
        ),
        migrations.AddField(
            model_name='car',
            name='year',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='enginemodel',
            name='manufacturer',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='enginemodel',
            name='year',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='model',
            name='generation',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='showroom',
            name='estb',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='showroom',
            name='owner',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='engine',
            name='engineModel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='engines', to='showroom.enginemodel', unique=True),
        ),
        migrations.AddField(
            model_name='car',
            name='features',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='showroom.features'),
        ),
    ]
