# Generated by Django 4.2.3 on 2023-07-28 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('showroom', '0003_brand_logo_car_image_model_picture_staff'),
    ]

    operations = [
        migrations.RenameField(
            model_name='features',
            old_name='abs',
            new_name='abs_brakes',
        ),
        migrations.AddField(
            model_name='features',
            name='heated_seats',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='features',
            name='leather_seats',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='features',
            name='seating_Capacity',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='features',
            name='sunroof',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='features',
            name='torque',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='features',
            name='turboCharger',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='brand',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='engine',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='showroom.engine'),
        ),
        migrations.AlterField(
            model_name='model',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
