# Generated by Django 4.2.3 on 2023-07-28 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showroom', '0004_rename_abs_features_abs_brakes_features_heated_seats_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enginemodel',
            name='name',
        ),
        migrations.AddField(
            model_name='enginemodel',
            name='engine',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='enginemodel',
            name='type',
            field=models.CharField(choices=[('G', 'Gasoline'), ('D', 'Diesel')], max_length=100, null=True),
        ),
    ]
