# Generated by Django 4.2.3 on 2023-07-29 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('showroom', '0006_remove_car_features_remove_car_image_remove_car_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='features',
            name='car',
        ),
        migrations.AddField(
            model_name='features',
            name='model',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='features', to='showroom.model'),
        ),
    ]
